
# Enable the automatic discover port from eureka
server:
  port: 0


eureka:
  instance:
    # generate an instance with application name and a random number
    # Is a unique identifier for each microservice
    instance-id: ${spring.application.name}:${random.int}

spring:
  application:
    name: ms-payments
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payments?createDatabaseIfNotExist=true
    username: root
    password: Vincere7
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Resilience4J
resilience4j:
  circuitbreaker:
    instances:
      updateOrder:
        slidingWindowSize: 2
        # Indicate the minimum of request to enable the circuit breaker
        minimumNumberOfCalls: 2
        # Indicate that the time will remain once the state changes to open/semi-open
        waitDurationInOpenState: 50s