
# Server port 0 to automatic register on service registry (eureka)
server:
  port: 0

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Vincere7
        username: root
        url: jdbc:mysql://${URL_DATABASE_ORDER:localhost:3306}/orders?createDatabaseIfNotExist=true
    application:
      name: ms-order
    jpa:
      properties:
        hibernate:
          format_sql: true
      show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    # generate an instance with application name and a random number
    # Is a unique identifier for each microservice
    instance-id: ${spring.application.name}:${random.int}


