
# Server port 0 to automatic register on service registry (eureka)
server:
  port: 0

spring:
  application:
    name: ms-order
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${MYSQL_ORDER_DB_INSTANCE:localhost:3306}/orders?createDatabaseIfNotExist=true
      username: ${MYSQL_ORDER_DB_USER:root}
      password: ${MYSQL_ORDER_DB_PASSWORD:}

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    # generate an instance with application name and a random number
    # Is a unique identifier for each microservice
    instance-id: ${spring.application.name}:${random.int}


