server:
  port: 8761

spring:
  application:
    name: service-discovery

# is necessary to set a FALSE register-with-eureka and fetch-registry
# to tell that microservice is a server and not a client
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false