server:
  port: 8082

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      client:
        # setup the provider token
        provider:
          spring:
            token-uri: http://localhost:9000/oauth2/token
        # setup oauth client
        registration:
          api-gateway:
            provider: spring
            client-id: api-gateway
            client-secret: secret
            client-name: api-gateway
            authorization-grant-type: client_credentials
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: '*'
            allowed-methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
            allowed-headers: '*'
      discovery:
        # Tells to service discovery to find the api-gateway
        # this will redirect all requests to api-gateway
        locator:
          enabled: true
          # enable application's name in lower case
          lower-case-service-id: true
      routes:
        - id: ms-order
          uri: http://localhost:8082/ms-order
          predicates:
            - Path=/ms-order/**
          filters:
            - TokenRelay=
            - RequestHeaderSize=1000B
        - id: ms-payments
          uri: http://localhost:8082/ms-payments
          predicates:
            - Path=/ms-payments/**
          filters:
            - TokenRelay=
            - RequestHeaderSize=1000B

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}

logging:
  level:
    com.netflix.eureka: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    security: DEBUG
    web: DEBUG
