server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              # Tells to service discovery to find the api-gateway
              # this will redirect all request to api-gateway
              lower-case-service-id: true
          httpclient:
            connect-timeout: 1000 #ms
            response-timeout: 5s

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${server.port}:${random.value}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: gateway, health, info
  endpoint:
    gateway:
      enabled: true