apiVersion: v1
kind: ConfigMap
metadata:
  name: data
data:
  SERVER_HOST: "http://service-discovery-0.service-discovery:8761/eureka,http://service-discovery-1.service-discovery:8761/eureka"
  DB_HOST: "mysql"
