apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: laurocorreia/api-gateway:1.0.1
          env:
            - name: SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: data
                  key: SERVER_HOST
            - name: EUREKA_URL
              valueFrom:
                configMapKeyRef:
                  name: data
                  key: SERVER_HOST
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-order
  labels:
    app: ms-order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-order
  template:
    metadata:
      labels:
        app: ms-order
    spec:
      containers:
        - name: ms-order
          image: laurocorreia/ms-order:1.0.2
          env:
            - name: SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: data
                  key: SERVER_HOST
            - name: MYSQL_ORDER_DB_INSTANCE
              valueFrom:
                configMapKeyRef:
                  name: data
                  key: DB_HOST
            - name: MYSQL_ORDER_DB_USER
              valueFrom:
                secretKeyRef:
                  name: passwords
                  key: DB_USER
            - name: MYSQL_ORDER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: passwords
                  key: DB_MYSQL_PASSWORD
            - name: EUREKA_URL
              valueFrom:
                configMapKeyRef:
                  name: data
                  key: SERVER_HOST
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment # StateFulSet has state, store data and respect deployment order. That is the difference between it and StatefulSet.
metadata:
  name: ms-payments
  labels:
    app: ms-payments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-payments
  template:
    metadata:
      labels:
        app: ms-payments
    spec:
      containers:
        - name: ms-payments
          image: laurocorreia/ms-payments:1.0.2
          env:
            - name: SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: data
                  key: SERVER_HOST
            - name: MYSQL_PAYMENTS_DB_INSTANCE
              valueFrom:
                configMapKeyRef:
                  name: data
                  key: DB_HOST
            - name: MYSQL_PAYMENTS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: passwords
                  key: DB_USER
            - name: MYSQL_PAYMENTS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: passwords
                  key: DB_MYSQL_PASSWORD
            - name: EUREKA_URL
              valueFrom:
                configMapKeyRef:
                  name: data
                  key: SERVER_HOST
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: apps/v1
kind: StatefulSet # StatefulSet does not have state or store data
metadata:
  name: service-discovery
spec:
  selector:
    matchLabels:
      app: service-discovery # has to match .spec.template.metadata.labels
  serviceName: "service-discovery"
  replicas: 2
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: service-discovery # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: service-discovery
          image: laurocorreia/service-discovery:1.0.3
          ports:
            - containerPort: 8761
              name: svc-discovery
          env:
            - name: SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: data
                  key: SERVER_HOST
            - name: EUREKA_HOSTNAME
              value: "service-discovery"