apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service-discovery
spec:
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    app: service-discovery
  type: LoadBalancer

---
# gateway-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  ports:
    - port: 8082
      targetPort: 8082
  type: LoadBalancer